### ISSUE TITLE
NULL CLOB: ORA-01405: fetched column value is NULL

### ISSUE THREAD

**Issue by fidli** [tassoevan/pdo-oci-extension#4]
more specific message:
OCIStmtFetch: ORA-01405: fetched column value is NULL (/tmp/tmp2/PDO_OCI-1.0/oci_statement.c:446)

from config, OCIStmtFetch2 function is used

Driver otherwise functions properly.

I cannot seem to find any solution.

on the php side, the pdo objects is used

```
			        $this->pdoStatement = $connection->getPdo()->prepare($queryString);
				$this->pdoStatement->setFetchMode(PDO::FETCH_ASSOC);
				$this->pdoStatement->execute($params);

```
The table has nullable CLOB with some rows having NULL value in that. 

I followed your guide. My oracle sdk&basic version are 12.2.0.1 so I just switched the numbers.

Php is PHP 5.6.30-0+deb8u1 (cli) (built: Feb  8 2017 08:50:21)
installed through apt-get

I have read in some threads, that it has been fixed. That I can confirm - on windows wamp, i have no problems with this. But following your guide, I ran to this problem...

Can you repro this issue with your whatever setup? or do you need more specific info?

Maybe there is wrong php inlclude or something. A flag of some sort....

If you need more info, I will give you that...

Thanks for your guide,

**Comment by tassoevan** [comment]
I believe you provided all the information needed to solve this. I haven't worked with Oracle databases for a while, so I have to ask you for some patience while I warm up and write a test for this issue. I'll update this issue according my accomplishments.

**Comment by fidli** [comment]
Thanks,
no problem. If you need more info, just ask.

**Comment by tassoevan** [comment]
I finally was able to reproduce it.
